---
abstract: 'Make your session data an object'
author:
  - 'Dave Rolsky, E<gt>autarch@urth.orgE<lt>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.35
generated_by: 'Module::Build version 0.351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-AsObject
provides:
  Catalyst::Plugin::Session::AsObject:
    file: lib/Catalyst/Plugin/Session/AsObject.pm
    version: 0.04
requires:
  Catalyst::Plugin::Session: 0.27
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
